== Errata

Hello readers!  

New versions of Angular are being released and we are committed to maintain the book code samples working. At the time of this writing, the latest version of this framework is Angular 4.0.0. You can find the Angular CLI version of book code samples migrated to Angular 4.0.0 in the directory extras in the above GitHub repository.

If you find any errors in https://www.manning.com/books/angular-2-development-with-typescript[Angular 2 Development with TypeScript] not listed below, it would be most appreciated if you would post the issues in the book's Author's Online Form in its Errata section so that they may be collected for everyone's benefit. 

=== Chapter 1


=== Chapter 2

*Page 26*. Listing 2.2. One code callout reads "Inside the constructor, you initialize the name property with the value
Angular 2 bound to the template." The digit 2 has to be removed from this text.

*Page 55*. Remove the second *the* from the following text fragment: "you’ll create the three the most interesting components".

=== Chapter 3

*Page 92*. The sentence that starts with "Note the parentheses" should read "Note the parentheses in the URL of the auxiliary route, http://localhost:8080/#/home(aux:chat)". 

*Page 95*. The text fragment "RootModule and BrowserModule" should read "RouterModule and BrowserModule".

*Page 99*. Remove *we* in "you we didn’t declare"

*Page 100*. Add Step 7 with the following content:

Add the following line to system.config.js:

[source, js]
----
'@angular/router' : {main: 'router.umd.min.js'}
----

*Page 101*. Add the following import statement to Listing 3.21:

[source, js]
----
import { Product, ProductService } from '../../services/product-service';
----

=== Chapter 4


=== Chapter 5

*Page 157* Listing 5.4. A pair of parentheses is missing. Replace this line:

[source, js]
----
console.log(`The price of ${stock} is ${100*Math.random().toFixed(4)}`);
----

with this one:

[source, js]
----
console.log(`The price of ${stock} is ${(100*Math.random()).toFixed(4)}`);
----

*Page 163*. The correct link to the DatePipe is https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html

*Page 167*. Listing 5.9. Remove the line that imports FilterPipe from the code. In pre-release versions of Angular it was required, but then the declaration of pipes was moved to the module class. 

So the app.module.ts need the following import line:

[source, js]
----
import {FilterPipe} from "./components/pipes/filter-pipe";
----

Also, you should add FilterPipe to the list of declarations in @NgModule.



=== Chapter 6

*Page 175*. Listing 6.3.  Right above @NgModule insert the following code fragment (it exists in the code sample though):

[source, js]
----
class AppComponent {

    stockSymbol: string;
    price:number;

    priceQuoteHandler(event:IPriceQuote) {
        this.stockSymbol = event.stockSymbol;
        this.price = event.lastPrice;
    }
}
----

*Page 181*. Replace the text "When the value of the buy input property on OrderComponent changes," with "When the value of the stock input property on OrderComponent changes,"

*Page 185*. This page include the text "...encapsulated—the entire window is shown with the parent’s light green background." The word parent has to be replaced with teh word child.

=== Chapter 7


=== Chapter 8

*Page 249*. Listing 8.6. Add the following line to the dependencies section:

[source, js]
----
"reflect-metadata": "^0.1.10"
----

=== Chapter 9


=== Chapter 10

=== Appednix A

=== Appendix B