/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/core/src/application_init';
import * as import6 from '@angular/core/src/testability/testability';
import * as import7 from '@angular/core/src/application_ref';
import * as import8 from '@angular/core/src/linker/compiler';
import * as import9 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import10 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import11 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import12 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import13 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import14 from '@angular/core/src/linker/view_utils';
import * as import15 from '@angular/core/src/linker/dynamic_component_loader';
import * as import16 from '@angular/core/src/di/injector';
import * as import17 from './app.component.ngfactory';
import * as import18 from '@angular/core/src/application_tokens';
import * as import19 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import20 from '@angular/platform-browser/src/dom/events/key_events';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import23 from '@angular/core/src/console';
import * as import24 from '@angular/core/src/facade/exception_handler';
import * as import25 from '@angular/core/src/linker/component_resolver';
import * as import26 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import27 from '@angular/platform-browser/src/dom/animation_driver';
import * as import28 from '@angular/core/src/render/api';
import * as import29 from '@angular/core/src/security';
import * as import30 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import31 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _AppModule_3:import1.AppModule;
  _ExceptionHandler_4:any;
  _ApplicationInitStatus_5:import5.ApplicationInitStatus;
  _Testability_6:import6.Testability;
  _ApplicationRef__7:import7.ApplicationRef_;
  __ApplicationRef_8:any;
  __Compiler_9:import8.Compiler;
  __ComponentResolver_10:any;
  __APP_ID_11:any;
  __DOCUMENT_12:any;
  __HAMMER_GESTURE_CONFIG_13:import9.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_14:any[];
  __EventManager_15:import10.EventManager;
  __DomSharedStylesHost_16:import11.DomSharedStylesHost;
  __AnimationDriver_17:any;
  __DomRootRenderer_18:import12.DomRootRenderer_;
  __RootRenderer_19:any;
  __DomSanitizationService_20:import13.DomSanitizationServiceImpl;
  __SanitizationService_21:any;
  __ViewUtils_22:import14.ViewUtils;
  __IterableDiffers_23:any;
  __KeyValueDiffers_24:any;
  __DynamicComponentLoader_25:import15.DynamicComponentLoader_;
  __SharedStylesHost_26:any;
  constructor(parent:import16.Injector) {
    super(parent,[import17.AppComponentNgFactory],[import17.AppComponentNgFactory]);
  }
  get _ApplicationRef_8():any {
    if ((this.__ApplicationRef_8 == null)) { (this.__ApplicationRef_8 = this._ApplicationRef__7); }
    return this.__ApplicationRef_8;
  }
  get _Compiler_9():import8.Compiler {
    if ((this.__Compiler_9 == null)) { (this.__Compiler_9 = new import8.Compiler()); }
    return this.__Compiler_9;
  }
  get _ComponentResolver_10():any {
    if ((this.__ComponentResolver_10 == null)) { (this.__ComponentResolver_10 = this._Compiler_9); }
    return this.__ComponentResolver_10;
  }
  get _APP_ID_11():any {
    if ((this.__APP_ID_11 == null)) { (this.__APP_ID_11 = import18._appIdRandomProviderFactory()); }
    return this.__APP_ID_11;
  }
  get _DOCUMENT_12():any {
    if ((this.__DOCUMENT_12 == null)) { (this.__DOCUMENT_12 = import4._document()); }
    return this.__DOCUMENT_12;
  }
  get _HAMMER_GESTURE_CONFIG_13():import9.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_13 == null)) { (this.__HAMMER_GESTURE_CONFIG_13 = new import9.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_13;
  }
  get _EVENT_MANAGER_PLUGINS_14():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_14 == null)) { (this.__EVENT_MANAGER_PLUGINS_14 = [
      new import19.DomEventsPlugin(),
      new import20.KeyEventsPlugin(),
      new import9.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_13)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_14;
  }
  get _EventManager_15():import10.EventManager {
    if ((this.__EventManager_15 == null)) { (this.__EventManager_15 = new import10.EventManager(this._EVENT_MANAGER_PLUGINS_14,this.parent.get(import21.NgZone))); }
    return this.__EventManager_15;
  }
  get _DomSharedStylesHost_16():import11.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_16 == null)) { (this.__DomSharedStylesHost_16 = new import11.DomSharedStylesHost(this._DOCUMENT_12)); }
    return this.__DomSharedStylesHost_16;
  }
  get _AnimationDriver_17():any {
    if ((this.__AnimationDriver_17 == null)) { (this.__AnimationDriver_17 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_17;
  }
  get _DomRootRenderer_18():import12.DomRootRenderer_ {
    if ((this.__DomRootRenderer_18 == null)) { (this.__DomRootRenderer_18 = new import12.DomRootRenderer_(this._DOCUMENT_12,this._EventManager_15,this._DomSharedStylesHost_16,this._AnimationDriver_17)); }
    return this.__DomRootRenderer_18;
  }
  get _RootRenderer_19():any {
    if ((this.__RootRenderer_19 == null)) { (this.__RootRenderer_19 = import22._createConditionalRootRenderer(this._DomRootRenderer_18)); }
    return this.__RootRenderer_19;
  }
  get _DomSanitizationService_20():import13.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_20 == null)) { (this.__DomSanitizationService_20 = new import13.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_20;
  }
  get _SanitizationService_21():any {
    if ((this.__SanitizationService_21 == null)) { (this.__SanitizationService_21 = this._DomSanitizationService_20); }
    return this.__SanitizationService_21;
  }
  get _ViewUtils_22():import14.ViewUtils {
    if ((this.__ViewUtils_22 == null)) { (this.__ViewUtils_22 = new import14.ViewUtils(this._RootRenderer_19,this._APP_ID_11,this._SanitizationService_21)); }
    return this.__ViewUtils_22;
  }
  get _IterableDiffers_23():any {
    if ((this.__IterableDiffers_23 == null)) { (this.__IterableDiffers_23 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_23;
  }
  get _KeyValueDiffers_24():any {
    if ((this.__KeyValueDiffers_24 == null)) { (this.__KeyValueDiffers_24 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_24;
  }
  get _DynamicComponentLoader_25():import15.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_25 == null)) { (this.__DynamicComponentLoader_25 = new import15.DynamicComponentLoader_(this._Compiler_9)); }
    return this.__DynamicComponentLoader_25;
  }
  get _SharedStylesHost_26():any {
    if ((this.__SharedStylesHost_26 == null)) { (this.__SharedStylesHost_26 = this._DomSharedStylesHost_16); }
    return this.__SharedStylesHost_26;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._AppModule_3 = new import1.AppModule();
    this._ExceptionHandler_4 = import4._exceptionHandler();
    this._ApplicationInitStatus_5 = new import5.ApplicationInitStatus(this.parent.get(import5.APP_INITIALIZER,null));
    this._Testability_6 = new import6.Testability(this.parent.get(import21.NgZone));
    this._ApplicationRef__7 = new import7.ApplicationRef_(this.parent.get(import21.NgZone),this.parent.get(import23.Console),this,this._ExceptionHandler_4,this,this._ApplicationInitStatus_5,this.parent.get(import6.TestabilityRegistry,null),this._Testability_6);
    return this._AppModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import1.AppModule)) { return this._AppModule_3; }
    if ((token === import24.ExceptionHandler)) { return this._ExceptionHandler_4; }
    if ((token === import5.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import6.Testability)) { return this._Testability_6; }
    if ((token === import7.ApplicationRef_)) { return this._ApplicationRef__7; }
    if ((token === import7.ApplicationRef)) { return this._ApplicationRef_8; }
    if ((token === import8.Compiler)) { return this._Compiler_9; }
    if ((token === import25.ComponentResolver)) { return this._ComponentResolver_10; }
    if ((token === import18.APP_ID)) { return this._APP_ID_11; }
    if ((token === import26.DOCUMENT)) { return this._DOCUMENT_12; }
    if ((token === import9.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_13; }
    if ((token === import10.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_14; }
    if ((token === import10.EventManager)) { return this._EventManager_15; }
    if ((token === import11.DomSharedStylesHost)) { return this._DomSharedStylesHost_16; }
    if ((token === import27.AnimationDriver)) { return this._AnimationDriver_17; }
    if ((token === import12.DomRootRenderer)) { return this._DomRootRenderer_18; }
    if ((token === import28.RootRenderer)) { return this._RootRenderer_19; }
    if ((token === import13.DomSanitizationService)) { return this._DomSanitizationService_20; }
    if ((token === import29.SanitizationService)) { return this._SanitizationService_21; }
    if ((token === import14.ViewUtils)) { return this._ViewUtils_22; }
    if ((token === import30.IterableDiffers)) { return this._IterableDiffers_23; }
    if ((token === import31.KeyValueDiffers)) { return this._KeyValueDiffers_24; }
    if ((token === import15.DynamicComponentLoader)) { return this._DynamicComponentLoader_25; }
    if ((token === import11.SharedStylesHost)) { return this._SharedStylesHost_26; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__7.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);